apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-example-app
  template:
    metadata:
      labels:
        app: elastic-example-app
    spec:
      containers:
        - name: elastic-example-container
          image: elastic/elasticsearch:7.17.19
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
          - name: discovery.type
            value: "single-node"

---

apiVersion: v1
kind: Service
metadata:
  name: elastic-example-service
spec:
  selector:
    app: elastic-example-app
  ports:
    - name : "elastic-example-9200"
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name : "elastic-example-9300"
      protocol: TCP
      port: 9300
      targetPort: 9300

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-example-app
  template:
    metadata:
      labels:
        app: app-example-app
    spec:
      containers:
        - name: app-example-container
          image: wielh/elastic-minikube-example:latest
          ports:
            - containerPort: 7777

---

apiVersion: v1
kind: Service
metadata:
  name: app-example-service
spec:
  type: NodePort
  selector:
    app: app-example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7777

